version: 1.0.{build}

branches:
  only:
    - master

os: Windows Server 2012

clone_folder: c:\projects\xash\xash3d

build:
  project: xash.sln

  verbosity: normal

before_build:
  - mkdir C:\projects\xash\SDL2
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - 7z x SDL2-devel-2.0.3-VC.zip -oc:\projects\xash
  - cd c:\projects\xash
  - rmdir SDL2 /s /q
  - ren SDL2-2.0.3 SDL2
  - git clone -q --branch=master https://github.com/SDLash3D/halflife.git C:\projects\xash\halflife
  - git clone -q --branch=master https://github.com/SDLash3D/XashXT.git C:\projects\xash\XashXT
  - cd c:\projects\xash\xash3d

after_build:
  - move C:\projects\xash\SDL2\lib\x86\*.* c:\projects\xash\xash3d\Debug
  - 7z a xash3d-win.7z c:\projects\xash\xash3d\Debug
  - curl --upload-file xash3d-win.7z https://transfer.sh/xash3d-win.7z

notifications:

  - provider: Webhook
    url: https://webhooks.gitter.im/e/29ef45a57585978bf71a
